#billedbiblioteker: /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/testSource
billedbiblioteker: /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/Hovedmappe, /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/Iphoto og foto/Fotos Library.photoslibrary
#billedbiblioteker: /media/asbjorn/925bd160-9cb1-4f8c-b329-1a01a1555203/Billeder eksport til linux
#billedbiblioteker: /media/asbjorn/925bd160-9cb1-4f8c-b329-1a01a1555203/Iphoto og foto/Fotos Library.photoslibrary/Masters
tilBibliotek: /media/asbjoern/925bd160-9cb1-4f8c-b329-1a01a1555203/main
#tilBibliotek: /home/asbjorn/Skrivebord/tilMappe


#