sourceLibs: /media/asbjoern/a78b1484-dfe0-47b8-9e7e-0214b1caad70/fotoOrganiserOutput/2019, /media/asbjoern/a78b1484-dfe0-47b8-9e7e-0214b1caad70/import
destinationLib: /media/asbjoern/a78b1484-dfe0-47b8-9e7e-0214b1caad70/nyeMapper
#sourceLibs: /home/asbjoern/Desktop/hovedmappe, /home/asbjoern/Desktop/iphoto
#destinationLib: /home/asbjoern/Desktop/fotoorganiserOutput
noExifFolderName: noExif
